---
title: "analisis_activo"
format: 
  html:
    embed-resources: true
editor: visual
output: html_document
---

# Análisis de Activos

```{r}
library(quantmod)

```

```{r}
getSymbols("MEGACPO.MX", src = "yahoo", from = "2024-01-01")

```

Calculo de los estimados de para la dS

```{r}

data <- MEGACPO.MX$MEGACPO.MX.Close

S0 <- as.numeric(Cl(data)[nrow(data)])
S0
```

```{r}

log_returns <- diff(log(data))
log_returns
```

```{r}

mu <- 252*mean(log_returns,  na.rm = TRUE)
sigma <- sqrt(252)*sd(log_returns,  na.rm = TRUE)

```

```{r}
mu
sigma

sigma/mu
```

```{r}
dt = 1/252
t <- seq(0,1,length.out=253)
```

```{r}
W <- c(0,cumsum(sqrt(dt)*rnorm(252)))

St <- S0*exp((mu - 0.5*sigma^2)*t + sigma*W)

plot(t,St,type='l',xlab='Dias',ylab='Precio',main='Simulación del precio del activo')
```

```{r}

sim <- 100000

p_final_año <- numeric(sim)
p_final_meses <- numeric(sim)


for (i in 1:sim){
  
  W <- c(0,cumsum(sqrt(dt)*rnorm(252)))
  
  St <- S0*exp((mu - 0.5*sigma^2)*t + sigma*W)
  
  p_final_año[i] <- tail(St,1)
  
  p_final_meses[i] <- St[126] 
}
```

```{r}
hist(p_final_año, n=100)
```

```{r}
hist(p_final_meses, n=100)
```

```{r}
mean(p_final_meses>S0)
mean(p_final_meses<S0)
```

```{r}
mean(p_final_año>S0)
mean(p_final_año<S0)
```

```{r}
mean(p_final_año>1.21*S0)
mean(p_final_meses>1.3*S0)

```

```{r}
quantile(p_final_meses, 0.025)
quantile(p_final_meses, 0.972)
```

```{r}
quantile(p_final_año, 0.025)
quantile(p_final_año, 0.972)

```
